---
title: "ETL Pull IDEA Data"
author: "Steven Macapagal"
date: "2023-09-28"
output: html_document
---

## Setup

- Last modified: 2023-09-28
- Last deployed (development): 
- Last deployed (production): 

```{r setup_doc}
knitr::opts_chunk$set(echo = TRUE)

# allows pins to work from RSConnect 
httr::set_config(httr::config(ssl_verifypeer = FALSE, ssl_verifyhost = FALSE))
```

### Load libraries

```{r setup_libraries}
library(tidyverse)
library(ideadata)
library(sf)
```

### Define tables, parameters, functions

```{r define_tables}
df_counties_tx <- tribble(
  ~ state, ~ region, ~ county,
  
  "TX", "Austin", "Travis County",
  "TX", "Austin", "Hays County",
  "TX", "Austin", "Bastrop County",
  "TX", "Austin", "Williamson County",

  "TX", "El Paso", "El Paso County",
  
  "TX", "Greater Houston Area", "Harris County",
  "TX", "Greater Houston Area", "Montgomery County",

  "TX", "Permian Basin", "Midland County",
  "TX", "Permian Basin", "Ector County",
  
  "TX", "Rio Grande Valley", "Cameron County",
  "TX", "Rio Grande Valley", "Hidalgo County",
  "TX", "Rio Grande Valley", "Starr County",
  
  "TX", "San Antonio", "Bexar County",
  "TX", "San Antonio", "Comal County",
  
  "TX", "Tarrant County", "Tarrant County",
  "TX", "Tarrant County", "Parker County",
  "TX", "Tarrant County", "Burleson County",
)

df_counties_ips <- tribble(
  ~ state, ~ region, ~ county,
  
  "OH", "Cincinnati", "Hamilton County",
  
  "FL", "Jacksonville", "Duval County",
  "FL", "Tampa", "Hillsborough County",
  "FL", "Tampa", "Polk County" ,
  
  "LA", "Southern Louisiana", "East Baton Rouge Parish",
)

df_counties_all <- bind_rows(
  df_counties_tx,
  df_counties_ips
)

df_geolocated_schools <- read_csv(here::here("etl","GIS_sites_data_summary.csv"))%>%
  janitor::clean_names()%>%
  select(region:longitude)%>%
  distinct()
```


```{r define_parameters}
# IDEA-related parameters ----
CURRENT_ACADEMIC_YEAR <- "2023-2024"
CURRENT_SCHOOL_TERM_ID <- 3300

# other parameters ----

```


```{r define_functions}
## get_geocoded_schools(region)
## get IDEA schools and geocode

get_geocoded_schools <- function(region = NULL) {
  
  geocoded_schools <- get_schools() %>%
    inner_join(get_regions() %>%
                 filter(RegionDescription == region) %>%
                 select(RegionID),
               by = c("RegionID" = "RegionID")) %>%
    select(SchoolShortName, SchoolStreet, SchoolCity, SchoolState, SchoolZipCode) %>%
    collect() %>%
    distinct(SchoolShortName, .keep_all = TRUE ) %>%
    janitor::clean_names() %>%
    tidygeocoder::geocode(street = school_street,
                          city = school_city,
                          state = school_state,
                          postalcode = school_zip_code,
                          method = "geocodio")
  
  return(geocoded_schools)
  
}

## add_geocoded_school()
## creates geocoded sf object for a given site
## should be used with get_geocoded_schools() %>% add_geocoded_school()

add_geocoded_school <- function(.data,
                          school_short_name = NULL,
                          school_street = NULL,
                          school_city = NULL,
                          school_state = NULL,
                          school_zip_code = NULL,
                          lat = NULL,
                          long = NULL) {
  
  if ((hasArg(lat) & !hasArg(long)) | (!hasArg(lat) & hasArg(long))) {
    
    stop("Cannot create an sf object without both latitude and longitude. Provide both or leave both out.")
    
  }
  
  if (hasArg(lat) & hasArg(long)) {
    
    return(add_row(.data,
            school_short_name = school_short_name,
            school_street = school_street,
            school_city = school_city,
            school_state = school_state,
            school_zip_code = as.numeric(school_zip_code),
            lat = lat,
            long = long))
    
  }
  
  if (!hasArg(lat) & !hasArg(long)) {
    
    new_geocoded_school <- data.frame(school_short_name = school_short_name,
          school_street = school_street,
          school_city = school_city,
          school_state = school_state,
          school_zip_code = as.numeric(school_zip_code)) %>%
            mutate(school_zip_code = as.character(school_zip_code)) %>%
    tidygeocoder::geocode(street = school_street,
            city = school_city,
            state = school_state,
            postalcode = school_zip_code,
            method = "geocodio") %>%
      mutate(school_zip_code = as.numeric(school_zip_code))
    
    add_row(.data, new_geocoded_school)
    
  }
  
}

## st_as_sf_schools(.data, crs = "WGS84")
## takes a geocoded data frame and returns a simple features frame

st_as_sf_schools <- function(.data, crs = "WGS84") {
  
  sf_schools <- st_as_sf(.data, coords = c("long", "lat")) %>%
    st_set_crs("WGS84")
  
  return(sf_schools)
  
}

## get_geocoded_students(region)
## get IDEA students and geocode

get_geocoded_students <- function(region = NULL) {
  
  df_schools <- get_regions() %>%
    filter(RegionDescription == region) %>%
    select(RegionID,
           RegionDescription) %>%
    inner_join(get_schools() %>%
                 select(SchoolNumber,
                        SchoolName,
                        SchoolShortName,
                        RegionID),
               by = c("RegionID" = "RegionID"))
  
  df_students <- get_students() %>%
    filter(SchoolTermID == CURRENT_SCHOOL_TERM_ID) %>%
    select(StudentNumber,
           Grade = GradeLevelID,
           ECDFlag,
           SchoolNumber, 
           PhysicalStreet, 
           PhysicalCity, 
           PhysicalState, 
           PhysicalZIP) %>%
    inner_join(df_schools,
              by = c("SchoolNumber" = "SchoolNumber")) %>%
    filter(RegionDescription == region) %>%
    collect() %>%
    janitor::clean_names() # %>%
  
  # geocodio has a max of 10,000 students per query
  # this will compute how many queries need to be sent
  
  n_students <- nrow(df_students)
  n_groups <- ceiling(n_students / 10000)
  
  # n_groups == 1 is the original code
  
  if (n_groups == 1) {
    
    df_students_geocoded <- df_students %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
  } else if (n_groups == 2) {
    
    df_students_geocoded_1 <- df_students[1:10000, ] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    df_students_geocoded_2 <- df_students[10001:n_students, ] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    df_students_geocoded <- bind_rows(
      df_students_geocoded_1,
      df_students_geocoded_2
    )
    
  } else if (n_groups == 3) {
    
    df_students_geocoded_1 <- df_students[1:10000, ] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    df_students_geocoded_2 <- df_students[10001:20000, ] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    df_students_geocoded_3 <- df_students[20001:n_students, ] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    df_students_geocoded <- bind_rows(
      df_students_geocoded_1,
      df_students_geocoded_2,
      df_students_geocoded_3
    )
    
  } else if (n_groups == 4) {
    
    df_students_geocoded_1 <- df_students[1:10000,] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    df_students_geocoded_2 <- df_students[10001:20000, ] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    df_students_geocoded_3 <- df_students[20001:30000, ] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    df_students_geocoded_4 <- df_students[30001:n_students, ] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    df_students_geocoded <- bind_rows(
      df_students_geocoded_1,
      df_students_geocoded_2,
      df_students_geocoded_3,
      df_students_geocoded_4
    )
    
  } else if (n_groups == 5) {
    
    df_students_geocoded_1 <- df_students[1:10000,] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    message("Group 1 (10000 cumulative observations) completed")
    
    df_students_geocoded_2 <- df_students[10001:20000, ] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    message("Group 2 (20000 cumulative observations) completed")
    
    df_students_geocoded_3 <- df_students[20001:30000, ] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    message("Group 3 (30000 cumulative observations) completed")
    
    df_students_geocoded_4 <- df_students[30001:40000, ] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    message("Group 4 (40000 cumulative observations) completed")
    
    df_students_geocoded_5 <- df_students[40001:n_students, ] %>%
      tidygeocoder::geocode(street = physical_street,
                            city = physical_city,
                            state = physical_state,
                            postalcode = physical_zip,
                            method = "geocodio")
    
    message(paste0("All groups (", n_students, " cumulative observations) completed"))
    
    df_students_geocoded <- bind_rows(
      df_students_geocoded_1,
      df_students_geocoded_2,
      df_students_geocoded_3,
      df_students_geocoded_4,
      df_students_geocoded_5
    )
    
  }
  
  return(df_students_geocoded)
  
}

## st_as_sf_students(.data, crs = "WGS84")
## takes a data frame and returns a special features object with defined CRS

st_as_sf_students <- function(.data, crs = "WGS84") {
  
  sf_students <- filter(.data, !(is.na(long))) %>%
    st_as_sf(coords = c("long", "lat")) %>%
    st_set_crs(crs)
  
  return(sf_students)
  
}

```

## Pull data

```{r pull_data}
# list is 20% memory of data frame
list_sf_geocoded_students <- df_counties_all %>%
  distinct(region) %>%
  # df:
  # ~ region
  pmap(get_geocoded_students) %>%
  map(., ~ st_as_sf_students(.x))


```

```{r}
list_sf_geocoded_schools <- df_counties_all %>%
  distinct(region) %>%
  # df:
  # ~ region
  pmap(get_geocoded_schools) %>%
  map(., ~ st_as_sf_schools(.x))

```

